# Generated by Django 4.2.23 on 2026-01-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0003_remove_activity_destination_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "cuisine_type",
                    models.CharField(
                        help_text="Cuisine type from search (e.g., 'Italian', 'Mexican')",
                        max_length=100,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Average rating (0.0 - 5.0)",
                        max_digits=2,
                        null=True,
                    ),
                ),
                (
                    "user_ratings_total",
                    models.IntegerField(default=0, help_text="Total number of reviews"),
                ),
                (
                    "price_level",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "$"), (2, "$$"), (3, "$$$"), (4, "$$$$")],
                        help_text="Price level from Google Places API",
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "google_place_id",
                    models.CharField(
                        help_text="Google Places API unique identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "maps_url",
                    models.URLField(
                        blank=True, help_text="Google Maps URL", max_length=500
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary from reviews"
                    ),
                ),
                (
                    "summary_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the summary was last generated",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="TripRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuisine_search_type",
                    models.CharField(
                        help_text="Which cuisine search this came from (e.g., 'italian')",
                        max_length=100,
                    ),
                ),
                (
                    "is_selected",
                    models.BooleanField(
                        default=False,
                        help_text="Has user chosen to keep this restaurant?",
                    ),
                ),
                (
                    "search_batch",
                    models.IntegerField(
                        default=1,
                        help_text="Which generation batch (for tracking regenerations)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_associations",
                        to="food.restaurant",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_restaurants",
                        to="api.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["cuisine_type"], name="food_restau_cuisine_cd576f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["rating"], name="food_restau_rating_7df6b5_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["google_place_id"], name="food_restau_google__c7f94d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="triprestaurant",
            index=models.Index(
                fields=["trip", "cuisine_search_type", "is_selected"],
                name="food_tripre_trip_id_4bdbce_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="triprestaurant",
            unique_together={("trip", "restaurant", "cuisine_search_type")},
        ),
    ]
