# Generated by Django 4.2.23 on 2025-09-05 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0002_alter_activity_options_flight_aircraft_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_conversation",
                        to="api.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locations", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="destination_search.tripconversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_user", models.BooleanField()),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="destination_search.tripconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConversationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("initial", "Getting Initial Preferences"),
                            ("generating_questions", "Generating Clarifying Questions"),
                            ("asking_clarifications", "Asking Clarification Questions"),
                            (
                                "generating_destinations",
                                "Generating Destination Recommendations",
                            ),
                            ("destinations_complete", "Destinations Generated"),
                            ("commitment_detected", "User Committed to Destination"),
                        ],
                        default="initial",
                        max_length=50,
                    ),
                ),
                (
                    "user_info",
                    models.TextField(
                        default="", help_text="Accumulated user preferences and answers"
                    ),
                ),
                (
                    "question_queue",
                    models.JSONField(
                        default=list, help_text="Remaining questions to ask user"
                    ),
                ),
                (
                    "current_question_index",
                    models.IntegerField(
                        default=0, help_text="Track which question we're on"
                    ),
                ),
                (
                    "destinations_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw AI-generated destinations text",
                    ),
                ),
                ("questions_asked", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="destination_search.tripconversation",
                    ),
                ),
            ],
        ),
    ]
